### ISSUE TITLE
Still have the libssl problem

### ISSUE THREAD

**Issue by lizheng29** [codemonstur/embedded-redis#31]

**Comment by lizheng29** [comment]
after runing cmd blow
    - yum install openssl -y
    - ldconfig /usr/local/lib64/
  I still got the error : Caused by: java.io.IOException: Redis-server process appears not to have started. No output was found in standard-out. stdandard-err contains this: /tmp/redis-3986587967364448550/redis-server-6.2.6-v5-linux-amd64: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory  

could you please see this?

**Comment by codemonstur** [comment]
I'm inclined to believe the redis binary when it says libssl.so.3 is not installed. There are a bunch of things that could be the problem. Maybe you installed the wrong version of openssl, maybe it was installed in the wrong location, maybe the redis binary can't find it because the proper location isn't configured, maybe gremlins. Google pointed to this stackoverflow article:

https://stackoverflow.com/questions/54124906/openssl-error-while-loading-shared-libraries-libssl-so-3

You can start there.
Here is another stackoverflow question:

https://superuser.com/questions/1765789/what-is-the-difference-between-libssl-so-3-and-libssl3-so

A guy in the comments suggests using this command: `yum whatprovides <path>`. So for you: `yum whatprovides /usr/lib64/libssl.so.3` or perhaps `yum whatprovides /usr/local/lib64/libssl.so.3`

**Comment by lizheng29** [comment]
Sincerely thank you，I will try that !

**Comment by jasonberanek** [comment]
@codemonstur : Perhaps should go in another thread, but should we expect the redis binaries to be statically compiled vs dynamically compiled and needing local objects? 

It seems [redis-server-6.2.7-linux-386](https://github.com/codemonstur/embedded-redis/blob/master/src/main/resources/redis-server-6.2.7-linux-386) is statically compiled, and able to run on hosts that have either OpenSSL 1.1 or OpenSSL 3.x (e.g., Ubuntu 20.04 and 24.04 respectively). But,  in testing [redis-server-6.2.6-v5-linux-amd64](https://github.com/codemonstur/embedded-redis/blob/master/src/main/resources/redis-server-6.2.6-v5-linux-amd64) expects to have it's dependency included dynamically at runtime, and fails if the specific OpenSSL versions are not installed.

**Comment by codemonstur** [comment]
@jasonberanek The requirement that OpenSSL is available on the host keeps tripping people up. I've actually gone out of my way to make the error handling as obvious as possible because I keep getting issues posted about it. Static or dynamic linking doesn't even come into it, it would probably be better to just remove SSL support entirely. People use the library for integration testing, why would you need SSL? 

The binaries in this project have always been the problem. There are no official binaries from an authoritative source. The Redis guys themselves don't release any. People have on occasion provided binaries, but accepting binaries from some random dude on the internet will always involve security risk. I could compile them myself, but I don't really want to be responsible for that. Even if I was, I don't have access to every platform and chipset out there, I would still have to get some from somewhere.

In my opinion, it would be better not to use embedded-redis at all. Mine or anyone else's. A better, more stable solution would be to use a pure Java Redis mock. No messing around with binaries, no leftover files, no SSL or library nonsense. I'm also slightly annoyed that of all the software I maintain, this project has the most number of stars. I only forked it because the Java code was really broken and needed to be cleaned up.

**Comment by ehayik** [comment]
I fixed using [redis-server-6.2.7-linux-386](https://github.com/codemonstur/embedded-redis/blob/master/src/main/resources/redis-server-6.2.7-linux-386)

```java
       if (System.getProperty("os.name").contains("Linux")) {
            var execFile = Paths.get(createTempDirectory("redis-").toString(), "redis-server-6.2.7-linux-386")
                    .toFile();
            var serverExecURL = RedisServer.class.getClassLoader().getResource("redis-server-6.2.7-linux-386");
            IOUtils.copy(requireNonNull(serverExecURL), execFile);
            var canExecute = execFile.setExecutable(true);

            log.info(
                    "Creating RedisServer using executable: {}, canExecute: {}, context: {}",
                    execFile,
                    canExecute,
                    context.getId());

            return new RedisServer(redisPort, execFile);
        }

        log.info("Creating RedisServer using default executable, context: {}", context.getId());
        return new RedisServer(redisPort);
```

@codemonstur: Is there a better way to provide the redis-server-6.2.7-linux-386 binary?

**Comment by codemonstur** [comment]
@ehayik It doesn't look like your question is connected to the libssl problem. For future reference; if you have a specific problem it would be better to create a separate issue for that. With respect to your question, I have no idea what you are attempting to do. If you just want to run a single server you can use the normal way of calling the builder. Look at [this](https://github.com/codemonstur/embedded-redis/blob/master/src/test/java/redis/embedded/RedisServerTest.java#L98) unit test to get an idea.

**Comment by codemonstur** [comment]
OP hasn't responded in a while. I'm assuming the problem was solved.

**Comment by lizheng29** [comment]
@codemonstur I tried everything.  It`s still not work on the docker linux system. but work on my windows PC. Maybe we can just use the real  redis on docker to do my unit test. I can`t find any other way

**Comment by codemonstur** [comment]
@lizheng29 You are kinda hijacking some other issue here. And you didn't provide me any errors or information to go on. That said, you can probably get the code to work with an existing installed redis binary. The `ExecutableProvider` is a nice functional interface so all you have to do is write code that detects if a redis binary exists and fall back to the default provider if it doesn't.

**Comment by lizheng29** [comment]
can I  use a binary that doesn't have TLS support. How can I do that?

**Comment by lizheng29** [comment]
we changed the docker image and solved it  ~~
